### ISSUE TITLE
yarn test fails for latest build

### ISSUE THREAD

**Issue by danirayan** [Anchor-Protocol/eth-anchor-contracts#11]
26 passing (46s)
  1 failing

  1) EthAnchorFactory
       "before all" hook: initialize ContractFactory in "EthAnchorFactory":
     HardhatError: HH700: Artifact for contract "TerraUSD" not found.
      at Artifacts._getArtifactPathFromFiles (node_modules/hardhat/src/internal/artifacts.ts:391:13)
      at Artifacts._getArtifactPath (node_modules/hardhat/src/internal/artifacts.ts:316:17)
      at Artifacts.readArtifact (node_modules/hardhat/src/internal/artifacts.ts:49:26)
      at getContractFactoryByName (node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:100:20)

Thanks for open sourcing this amazing project. Any pointers to locate this artifact would be of great help cc @frostornge @unifiedh

**Comment by luckypal** [comment]
Any luck here?
